version: "3.9"
services:
  instauto:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - IS_RUNNING_ON_DOCKER=true
    entrypoint: ["node", "/app/instauto/src/start.ts"]
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
    profiles: ["instauto"]
